import Head from "next/head"
import Image from "next/image"
import Header from "../components/Header"
import styles from "../styles/Home.module.css"
import WidgetCard from "../components/WidgetCard"
import StackedBarChart from "../components/StackedBarChart"
import NotificationItem from "../components/NotificationItem"
import LocationItem from "../components/LocationItem"
import { Inter } from "@next/font/google"
import Dashboard from "./Dashboard"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/ilaundry-logo.png" />
      </Head>
      <main>
        <Header />
        {/* <WidgetCard /> */}
        {/* <StackedBarChart /> */}
        {/* <NotificationItem /> */}
        {/* <LocationItem /> */}
      </main>
    </>
  )
}
